loadbalancers:
  - name: entry-ru
    externalIPs:
      - "213.178.155.151"
  - name: entry-hk
    externalIPs:
      - "74.119.193.216"
  - name: entry-us
    externalIPs:
      - "195.149.87.172"

deployment:
  name: entry
  replicas: 6
  image: cr.yandex/crpftiduupc1q0p2dmgt/entry
  version: "0.1.19"
  pullSecrets: regcred