apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: {{ $.Values.component }}
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/version: {{ $.Values.version }}
  name: {{ $.Values.name }}
  namespace: {{ $.Values.namespace }}