---
- name: Reload Daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: restarted