---
- name: Reload Prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Restart Prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: restarted