apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-us
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      node: node-us
  template:
    metadata:
      labels:
        app: web
        node: node-us
    spec:
      nodeSelector:
        node: node-us
      containers:
      - name: web
        image: cr.yandex/crpftiduupc1q0p2dmgt/web:0.5
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      imagePullSecrets:
      - name: regcred
