apiVersion: v1
kind: Service
metadata:
  name: lb-service-ru
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: web
    node: node-ru
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
