---
main_text: "Something went wrong! Make sure that Grafana is up and running."
main_title: "Grafana"
nginx_http_config: |+
  server {
      listen 80;
      listen [::]:80;
      server_name grafana.olegrumpy.ru;

      # Redirect all HTTP requests to HTTPS
      return 301 https://$server_name$request_uri;
  }

  # HTTPS
  server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;
      server_name grafana.olegrumpy.ru;

      ssl_certificate /etc/ssl/bundle.crt;
      ssl_certificate_key /etc/ssl/certificate.key;

      root /var/www/html;
      index index.html index.htm index.nginx-debian.html;

      location / {
          proxy_set_header Host grafana.olegrumpy.ru;
          proxy_set_header Origin https://grafana.olegrumpy.ru;
          proxy_pass http://localhost:3000;
          proxy_intercept_errors on;
          error_page 500 502 503 504 = @fallback;
      }
  
      location @fallback {
          try_files /index.html =404;
      }
  }