{{- range .Values.loadbalancers }}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service-{{ .name }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs: {{ .externalIPs }}
  selector:
    app: {{ $.Values.deployment.name }}
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
{{- end }}
