---
- name: Open common ports
  become: true
  ansible.builtin.shell: "ufw allow {{ item }}"
  loop:
    - 22
    - 80
    - 443
  tags:
    - nginx

- name: Enable ufw
  become: true
  ansible.builtin.shell: "ufw --force enable"
  tags:
    - nginx

- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
  tags:
    - nginx

- name: Copy Certificates Bundle
  become: true
  ansible.builtin.copy:
    src: "bundle.crt"
    dest: "/etc/ssl/"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart Nginx
  tags:
    - nginx

- name: Copy Certificate Key
  become: true
  ansible.builtin.copy:
    src: "certificate.key"
    dest: "/etc/ssl/"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - nginx

- name: Start Nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx

- name: Copy Nginx Configuration file
  become: true
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart Nginx
  tags:
    - nginx

- name: Copy Nginx http config
  become: true
  ansible.builtin.copy:
    content: "{{ nginx_http_config }}"
    dest: "/etc/nginx/sites-available/default"
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart Nginx
  tags:
    - nginx

- name: Copy Index file
  become: true
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
  tags:
    - nginx
