---
- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy Certificates Bundle
  become: true
  ansible.builtin.copy:
    src: "bundle.crt"
    dest: "/etc/ssl/"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Copy Certificate Key
  become: true
  ansible.builtin.copy:
    src: "certificate.key"
    dest: "/etc/ssl/"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Start Nginx service
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Copy Nginx Configuration file
  become: true
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart Nginx

- name: Copy Nginx Server file
  become: true
  ansible.builtin.template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
  notify:
    - Restart Nginx

- name: Copy Index file
  become: true
  ansible.builtin.template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
