---
- name: Open common ports
  become: true
  ansible.builtin.shell: "ufw allow {{ item }}"
  loop:
    - 22
    - 53
    - 9153
  tags:
    - coredns

- name: Enable ufw
  become: true
  ansible.builtin.shell: "ufw --force enable"
  tags:
    - coredns

- name: Hardcode GitHub DNS records
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    create: yes
  loop:
    - "140.82.121.4 github.com"
    - "185.199.110.133 objects.githubusercontent.com"
  tags:
    - coredns

- name: Create coredns user
  become: true
  ansible.builtin.shell: useradd coredns || echo "User already exists."
  tags:
    - coredns

- name: Create workdir
  become: true
  ansible.builtin.shell: mkdir /etc/coredns || echo "Directory already exists."
  tags:
    - coredns

- name: Allow bind on ports < 1024
  become: true
  ansible.builtin.shell: echo 'net.ipv4.ip_unprivileged_port_start=0' > /etc/sysctl.d/99-unprivileged-ports.conf && sysctl -p /etc/sysctl.d/99-unprivileged-ports.conf
  tags:
    - coredns

- name: Copy CoreDNS binary
  become: true
  ansible.builtin.copy:
    src: "coredns"
    dest: "/usr/local/bin/"
    owner: "coredns"
    group: "coredns"
    mode: "0744"
  tags:
    - coredns

- name: Copy GeoLite DB
  become: true
  ansible.builtin.copy:
    src: "{{ database }}"
    dest: "/etc/coredns/"
    owner: "coredns"
    group: "coredns"
    mode: "0744"
  tags:
    - coredns

- name: Stop systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  tags:
    - coredns

- name: Copy coredns.service
  become: true
  ansible.builtin.template:
    src: "coredns.service.j2"
    dest: "/etc/systemd/system/coredns.service"
  notify:
    - Reload CoreDNS
  tags:
    - coredns

- name: Copy RU zone file
  become: true
  ansible.builtin.template:
    src: "db-ru.olegrumpy.ru.j2"
    dest: "{{ coredns_workdir }}/db-ru.olegrumpy.ru"
  notify:
    - Restart CoreDNS
  tags:
    - coredns

- name: Copy US zone file
  become: true
  ansible.builtin.template:
    src: "db-us.olegrumpy.ru.j2"
    dest: "{{ coredns_workdir }}/db-us.olegrumpy.ru"
  notify:
    - Restart CoreDNS
  tags:
    - coredns

- name: Copy ASIA zone file
  become: true
  ansible.builtin.template:
    src: "db-asia.olegrumpy.ru.j2"
    dest: "{{ coredns_workdir }}/db-asia.olegrumpy.ru"
  notify:
    - Restart CoreDNS
  tags:
    - coredns

- name: Copy primary Corefile
  become: true
  ansible.builtin.template:
    src: "Corefile.primary.j2"
    dest: "{{ coredns_workdir }}/Corefile"
  when: coredns_is_primary is defined and coredns_is_primary
  notify:
    - Restart CoreDNS
  tags:
    - coredns

- name: Copy secondary Corefile
  become: true
  ansible.builtin.template:
    src: "Corefile.secondary.j2"
    dest: "{{ coredns_workdir }}/Corefile"
  when: coredns_is_primary is defined and not coredns_is_primary
  notify:
    - Restart CoreDNS
  tags:
    - coredns

- name: Change owner of workdir
  become: true
  ansible.builtin.shell: chown -R coredns:coredns {{ coredns_workdir }}
  tags:
    - coredns

- name: Allow TCP/UDP on port 53
  become: true
  ansible.builtin.shell: ufw allow 53
  tags:
    - coredns

- name: Start CoreDNS
  become: true
  ansible.builtin.systemd:
    name: coredns
    state: started
    enabled: true
  tags:
    - coredns
