---
- hosts:
    - ns1_olegrumpy_ru
    - ns2_olegrumpy_ru
  roles:
    - coredns

- hosts:
    - olegrumpy_ru
    - olegrumpy_us
    - olegrumpy_hk
  any_errors_fatal: true
  roles:
    - k8s

- hosts:
    - monitoring
  roles:
    - nginx
    - prometheus
    - grafana
