{{- range .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: web
      node: {{ .nodeLabel }}
  template:
    metadata:
      labels:
        app: web
        node: {{ .nodeLabel }}
    spec:
      nodeSelector:
        node: {{ .nodeLabel }}
      containers:
      - name: web
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
      imagePullSecrets:
      - name: {{ $.Values.image.pullSecrets }}
{{- end }}
